### ISSUE TITLE
Fallback to node vim?

### ISSUE THREAD

**Issue by jladuval** [tomarrell/vim-npr#1]
Hi Tom! I wanted to submit this as a PR but my vimscript is abysmal. What I've ended up doing is pasting vim-npr into my node-vim plugin so that when node-vim can't find the file it falls back to vim-npr. It's a pretty hacky solution and I'm sure there's a proper way to do it.

Is it possible to detect if node-vim is installed and fallback to its file resolution if vim-npr can't resolve the file? It looks like node-vim exposes a NodeGotoFile function that could be used.

Also, I think the default `g:vim_npr_file_names` should be ` ["", ".js", "/index.js", "/index.jsx"]`
It seems logical since the the plugin activates inside jsx files anyway.

**Comment by tomarrell** [comment]
Hey thanks for the issue!

I've merged in an update to the default file names, thanks for the feedback on that. #2

I can definitely do some integration with vim-npr, I've had a look and I should be able to do some sort of fallback checking and then call the vim-node find method. I would be curious however as to the case that is currently failing resolution, as I might be better off solving that and any others to reach feature parity as far as resolution goes with vim-node.

Just using this myself on the day-to-day I have noticed it acting less ideally on a rather simple case of resolving index.js etc on something like './component', and it returning a directory view to then select the file manually, however I haven't been writing enough JS recently for this to bother me yet ;) 

If you want to just briefly describe the case/s then we can see where to go from there. Cheers!

**Comment by jladuval** [comment]
hahaha you described the exact case I hit today! Resolving index.js or index.jsx on directory imports.

**Comment by tomarrell** [comment]
Ok perfect, I will get that resolved and merge in a fix for that ASAP as that is definitely intended functionality.

Will let you know when it's in there so you can pull the update.

**Comment by tomarrell** [comment]
I've just made a 1.0 release which include a resolution for this issue. https://github.com/tomarrell/vim-npr/releases

The relative resolution should be working, I've also made improvements to node_module resolution for a couple of common patterns there.

I hope this has solved your problems! 😄

**Comment by tomarrell** [comment]
Oh also just thought I'd mention, if you're using Vim-plug as your package manager, you can easily fetch the latest release by using `:PlugUpdate vim-npr`

**Comment by jladuval** [comment]
Just tested it, working great! Thanks Tom.
