### ISSUE TITLE
Add support for 'open file in a new window'(<c-w> f) and 'open file in a new tab'(<c-w> gf)

### ISSUE THREAD

**Issue by kwikenkwak** [tomarrell/vim-npr#9]
There is currently no support for these two shortcuts. I would find it handy if I could use these as well and I suspect it is not too difficult to support these too.

**Comment by tomarrell** [comment]
Hey @kwikenkwak, unfortunately I don't really have the time to work on this lately. If you would like to look into implementing it, I would be happy to review a PR!
